### ISSUE TITLE
Unable to dereference schema with null value

### ISSUE THREAD

**Issue by curtisr7** [bojand/json-schema-deref#22]
1) What version of the module is the issue happening on? Does the issue happen on latest version?
0.3.4
2) What platform and Node.js version? (For example Node.js 0.12 on Mac OS X)
Node 4, osx
3) Sample source code or steps to reproduce

I have a schema that contains null values and I am unable to dereference when using a custom loader AND `failOnMissing:true`.

Example:

````
var Promise = require('bluebird');
var deref = Promise.promisify(require('json-schema-deref'));

var obj = {
  a: null,
  b: {
    $ref: './somevalue.txt'
  }
};

function loader(refValue, opts, cb) {
  if(!refValue) {
    // This shouldn't happen!!!
    return cb();
  }
  if (refValue && refValue === './somevalue.txt') {
    return cb(null, 'new-value');
  }
};

return deref(obj, { failOnMissing: true, loader: loader })
  .then(function (derefd) {
    console.log(derefd.b);
  }).catch(function (err) {
    console.log(err);
  });
````

When I run this code I get `{ [Error: Missing $ref: undefined] cause: [Error: Missing $ref: undefined], isOperational: true }`

I found that if I remove the `failOnMissing` option, or the null property everything works as expected.

**Comment by curtisr7** [comment]
and another flavor of most likely the same bug. Take the testcase above and change `obj` to 

`````
var obj = {
  swagger: '2.0',
  info: { 'x-name': 'my-api', title: 'my api', version: '1.0' },
  definitions: { user: { type: 'object', add: false } }
};
````

**Comment by MitMaro** [comment]
I'm running into the same issue (I think) when updating from version 0.3.3 to 0.3.4. I have attached a modified test case based on the tests:

## Test case

	const deref = require('json-schema-deref');
	
	// schema-dereference.js
	const testSchema = {
		"description": "Just a basic schema.",
		"title": "Basic Object",
		"type": "object",
		"properties": {
			"id": {
				"$ref": "db://custom.json#/id.json"
			}
		},
		"additionalProperties": false
	};
	
	return deref(testSchema, {
		failOnMissing: true,
		loader: (ref, options, fn) => {
			if (ref.indexOf('db:') === 0) {
				const value = {
					type: "string"
				};
				return fn(null, value);
			}
			
			return fn(null);
		}
	}, (err, newSchema) => console.log(newSchema));

### Version 0.3.3

	$ node schema-dereference.js
	{ description: 'Just a basic schema.',
	  title: 'Basic Object',
	  type: 'object',
	  properties: { id: { type: 'string' } },
	  additionalProperties: false }


### Using version: 0.3.4

	$ node schema-dereference.js
	/code/schema-dereference.js:19
	            if (ref.indexOf('db:') === 0) {
	                   ^
	
	TypeError: Cannot read property 'indexOf' of undefined
	    at loader (/code/schema-dereference.js:19:10)
	    at getRefSchema (/code/node_modules/json-schema-deref/dist/index.js:158:5)
	    at Object.<anonymous> (/code/node_modules/json-schema-deref/dist/index.js:325:5)
	    at traverseNode (/code/node_modules/traverse-async/lib/traverse-async.js:45:27)
	    at Object.process (/code/node_modules/traverse-async/node_modules/async/lib/async.js:806:21)
	    at next (/code/node_modules/traverse-async/node_modules/async/lib/async.js:803:27)
	    at /code/node_modules/traverse-async/node_modules/async/lib/async.js:32:16
	    at Object.<anonymous> (/code/node_modules/json-schema-deref/dist/index.js:311:14)
	    at traverseNode (/code/node_modules/traverse-async/lib/traverse-async.js:45:27)
	    at Object.process (/code/node_modules/traverse-async/node_modules/async/lib/async.js:806:21)

**Comment by francescoditrani** [comment]
Similar issue here with 0.3.4. 
node 6.2.0 on MAC and CoreOS

In my loader function I have an undefined ref. I've tried with failOnMissing true and false and it fails on both. The only solution is to return to 0.3.2
This is one of the schemas that expose the behaviour:
`{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties": {
		"alternateText": {
			"type": "string"
		},
		"default": {
			"type": "string"
		},
		"xl": {
			"type": "string"
		},
		"l": {
			"type": "string"
		},
		"m": {
			"type": "string"
		},
		"s": {
			"type": "string"
		},
		"options": {
			"$ref": "#/definitions/options"
		}
	},
	"definitions": {
		"options": {
			"type": "object",
			"properties": {
				"default": {
					"type": "string"
				},
				"xl": {
					"type": "string"
				},
				"l": {
					"type": "string"
				},
				"m": {
					"type": "string"
				},
				"s": {
					"type": "string"
				}
			},
			"additionalProperties": false
		}
	},
	"required": [
		"alternateText",
		"default"
	],
	"additionalProperties": false
}`
