### ISSUE TITLE
Undefined ref in custom loader.

### ISSUE THREAD

**Issue by francescoditrani** [bojand/json-schema-deref#23]
I have this issue with version 0.3.4. 
node 6.2.0 on MAC and CoreOS

In my loader function I have an undefined ref. Just to add some info: I've tried with failOnMissing true and false and I have an undefined ref with both. 
My current solution is to return to 0.3.2
This is one of the schemas that expose the behaviour:

`{ "$schema": "http://json-schema.org/draft-04/schema#", "type": "object", "properties": { "alternateText": { "type": "string" }, "default": { "type": "string" }, "xl": { "type": "string" }, "l": { "type": "string" }, "m": { "type": "string" }, "s": { "type": "string" }, "options": { "$ref": "#/definitions/options" } }, "definitions": { "options": { "type": "object", "properties": { "default": { "type": "string" }, "xl": { "type": "string" }, "l": { "type": "string" }, "m": { "type": "string" }, "s": { "type": "string" } }, "additionalProperties": false } }, "required": [ "alternateText", "default" ], "additionalProperties": false }`

**Comment by MitMaro** [comment]
I believe this is the same issue that is reported in #2
