### ISSUE TITLE
is it possible to move up your dep to request 2.83.0 to solve vulunerabiltiy issue?

### ISSUE THREAD

**Issue by smartmouse** [bojand/json-schema-deref#26]
1) What version of the module is the issue happening on? Does the issue happen on latest version?
0.3.x

2) What platform and Node.js version? (For example Node.js 0.12 on Mac OS X)
node 6.11.3
3) Sample source code or steps to reproduce

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

Reason for the ask is to shy away from tough-cookie@2.2.2 which has vulunerbility issues
request@2.83.0 depends on newer version of tough-cookie@.2.3.x and the vulunerabiltiy
is resolved.

 `-- json-schema-deref@0.3.2
   `-- request@2.70.0
     `-- tough-cookie@2.2.2

Thanks

**Comment by bojand** [comment]
Should be fixed and published as 0.3.6.

**Comment by smartmouse** [comment]
Thank you so much for your help and much apreciated! You are aswesome!
