### ISSUE TITLE
dependency clone@1.02 has XSS vulunerabilty

### ISSUE THREAD

**Issue by smartmouse** [bojand/json-schema-deref#27]
1) What version of the module is the issue happening on? Does the issue happen on latest version?
0.3.6
2) What platform and Node.js version? (For example Node.js 0.12 on Mac OS X)
any

3) Sample source code or steps to reproduce

see warning of XSS vulnerability  during install.

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

The dependency in your package.son had clone@1.0.2  which causes vulunerability
Please help to fix it.

npm WARN deprecated clone@1.0.2: XSS vulnerability fixed in v1.0.3

**Comment by attritionorg** [comment]
@smartmouse Have a reference for the vuln? Don't see mention on https://github.com/pvorb/clone or Snyk. Thanks

**Comment by smartmouse** [comment]
Hello: This is what I saw in the warnings 

```
:~ smartmouse$ npm i -g apiconnect@apic-v5.0.6.5
npm WARN deprecated crypto@0.0.3: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm WARN deprecated clone@1.0.2: XSS vulnerability fixed in v1.0.3
npm WARN deprecated node-uuid@1.4.7: Use uuid module instead
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

```

**Comment by smartmouse** [comment]
hey Thanks for fixing this but I have an issue

you original dependencies is
    "clone": "~1.0.2",

Now you make it "clone": "~2.0.0"
That will require major version change.
Is it possible to do  "clone": "~1.0.3" or  "clone": "^1.0.3"   ?

**Comment by bojand** [comment]
Can you elaborate why is this an issue?
The API did not change (for `json-schema-deref`). 
Additionally since we use `clone` only to clone the input schema, the changes in `clone` 2.x are not very relevant to our usage to potentially introduce any regressions.
All tests pass.

**Comment by smartmouse** [comment]
Good to hear that . Then It is likely not an issue.

we have a shrinkwrap file generated and we are maintaining and avoid regen
the shrinkwrap file to keep stability and keep change to minimal.
But anyways. as long as no regression, all is good. Thank you for your
prompt reply.
